version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm pack
  post_build:
    commands:
      - echo Build completed on `date`
      - sam deploy --template-file template.yml --stack-name ben-pipeline-alerter-stack --capabilities CAPABILITY_IAM
artifacts:
  files:
    - pipeline-alerter-1.0.0.tgz